-- Phase 3.5: notification audit log + resend support

create table if not exists order_notifications (
  id bigint generated by default as identity primary key,
  order_id uuid not null references orders(id) on delete cascade,
  template text not null,
  was_forced boolean not null default false,
  status text not null check (status in ('sent', 'failed', 'skipped')),
  error_detail text,
  created_at timestamptz not null default now()
);

create index if not exists order_notifications_order_id_idx on order_notifications(order_id, created_at desc);

alter table order_notifications enable row level security;

drop policy if exists "auth read order notifications" on order_notifications;
create policy "auth read order notifications"
  on order_notifications for select
  to authenticated
  using (true);

